### ISSUE TITLE
 synergy statement

### ISSUE THREAD

**Issue by fedhere** [fedhere/Explosive-Physics-Fast-Transients-White-Paper-Cadence#13]
review Bricam, Street (Galactic Plane), Gezari, and Bell & Lund for synergy as recommanded by the TAC. Incorporated a sentence about the synergy in section Performance

**Comment by MelissaGraham** [comment]
I noticed that Section 3.12, Item 5, requests a discussion of trade-offs "with others [proposals] which may have similar but slightly different requests" so that's where I'm writing about each of these in turn. Work in progress.

**Comment by tylerapritchard** [comment]
Thank you Melissa!  A few comments:

I added a small blurb to the Street et al. comment's last sentence to highlight that our cadence should have some benefit to the variable star peeps as well:  
"... and some synergy as this would potentially extend the variable star identification from only the galactic plane to the galactic halo as well"

Gezari et al. - I think this may be worth some small discussion.  There's a whole lot of trade-off here and I, personally, might want to soften this as this would potentially increase our fast transient detection rate (since the whole WFD is at high cadence) at the noted cost of long term monitoring (but which could potentially be performed by other telescopes in many cases) and would increase the ability to study some forms of fast-er transients with LSST only. I agree it's not ideal, but perhaps:

 "We would advocate the 'Extreme Rolling Cadence' as suitable for only a portion of the WFD Footprint as the Gezari et al. proposal has significant impact on the ability to long-term monitor transients with fast features (e.g. Type IIn SNe which can last for years), although our observation filter strategy may be broadly complementary to their goals."  

I didn't modify what we had in there, but did put in a note with the above. 

I added a small blurb for Bell thatI  had already written, mostly trying to stress that that's not a replacement for our needs: 

(4) Bell et al. "Continuous Cadence Acquisition of the LSST Deep Drilling Fields", proposes to do the DDF as a series of 1-2 hours of continuous observations in a particular filter and with a focus on the Galactic Plane, LMC, and SMC.  While the high cadence is complementary to our goals, emphasis on the galactic plane and low volume of the DDF means that the relatively rare extragalactic fast transients that we target in this survey are unlikely to be detected in significant numbers and the lack of color information will make it difficult to classify some events when prioritizing followup.  

Happy to see it removed if it's viewed as unnecessary.  Trying to understand the other Keaton proposal regarding aliasing a bit more to see if it's worth discussing at the moment, but I'm leaning towards no.

**Comment by MelissaGraham** [comment]
Hmmm, all else is OK with me, but I think I strongly disagree that an extreme rolling cadence in which zero images are obtained for any portion of WFD for seven out of the ten years of the LSST survey is something we want to "advocate" for. I updated the text to say this instead, which doesn't use the word "advocate" at all.

(3) Gezari et al. ``An Extreme Rolling Cadence Wide-Fast-Deep Survey", proposes to do the full WFD area in only years 1 and 10, and rotate through 8 equal strips of area in years 2 through 9. While this would often result in 2-3 visits per night, probably in multiple filters, no specific filter pairings or revisit timescales are requested. The trade-off between these proposals is that such an extreme rolling cadence would remove the opportunity for longer-term monitoring of transients with fast features, such as Type IIn SNe, which can last for years.

If this is OK, then I think once @tylerapritchard adds the blurb (4) for Bell et al., I think we can close the issue -- but also happy to discuss further.

**Comment by tylerapritchard** [comment]
I'm good with that @MelissaGraham , thanks - I agree actually. I think the "advocate" came across too strongly as well upon a re-read.  Although I may be a bit more receptive to Gezari et al.; all I was trying to say was that we would never want their cadence for the entire WFD, not for it in general.       

The Bell et al. note should should already be in there as well. Closing up then.
